apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: podinfo
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/sohel2020/kargo-flux-demo.git
  username: sohel2020
  password: REPLACE_WITH_PAT   # classic PAT with repo scope, or `gh auth token`
type: Opaque
