apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: podinfo
  namespace: podinfo
spec:
  promotionPolicies:
    - stageSelector:
        name: dev
      autoPromotionEnabled: true
