apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: demo
spec:
  requestedFreight:
    - origin: {kind: Warehouse, name: demo}
      sources: {direct: true}
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/sohel2020/kargo-flux-demo.git
            checkout:
              - branch: main
                path: ./repo
        - uses: yaml-update
          config:
            path: ./repo/apps/demo/dev/helmrelease.yaml
            updates:
              - key: spec.chart.spec.version
                value: ${{ chartFrom("oci://ttl.sh/demo-65250222/demo").Version }}
        - uses: git-commit
          config:
            path: ./repo
            message: 'promote demo dev to chart ${{ chartFrom("oci://ttl.sh/demo-65250222/demo").Version }}'
        - uses: git-push
          config: {path: ./repo}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage
  namespace: demo
spec:
  requestedFreight:
    - origin: {kind: Warehouse, name: demo}
      sources: {stages: [dev]}
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/sohel2020/kargo-flux-demo.git
            checkout:
              - branch: main
                path: ./repo
        - uses: yaml-update
          config:
            path: ./repo/apps/demo/stage/helmrelease.yaml
            updates:
              - key: spec.chart.spec.version
                value: ${{ chartFrom("oci://ttl.sh/demo-65250222/demo").Version }}
        - uses: git-commit
          config:
            path: ./repo
            message: 'promote demo stage to chart ${{ chartFrom("oci://ttl.sh/demo-65250222/demo").Version }}'
        - uses: git-push
          config: {path: ./repo}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: demo
spec:
  requestedFreight:
    - origin: {kind: Warehouse, name: demo}
      sources: {stages: [stage]}
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/sohel2020/kargo-flux-demo.git
            checkout:
              - branch: main
                path: ./repo
        - uses: yaml-update
          config:
            path: ./repo/apps/demo/prod/helmrelease.yaml
            updates:
              - key: spec.chart.spec.version
                value: ${{ chartFrom("oci://ttl.sh/demo-65250222/demo").Version }}
        - uses: git-commit
          config:
            path: ./repo
            message: 'promote demo prod to chart ${{ chartFrom("oci://ttl.sh/demo-65250222/demo").Version }}'
        - uses: git-push
          config: {path: ./repo}
