apiVersion: v1
kind: Namespace
metadata: {name: demo-dev}
---
apiVersion: v1
kind: Namespace
metadata: {name: demo-stage}
---
apiVersion: v1
kind: Namespace
metadata: {name: demo-prod}
---
apiVersion: v1
kind: Namespace
metadata: {name: demo}
